BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.DataAccess.Repository.IRepository;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the name");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(category);

        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
              var categoryFromFirstORDefaultDb= _unitOfWork.Category.GetFirstOrDefault(c => c.Id==id);
            //  var categoryFromSingleOrDefaultDb= _db.Categories.SingleOrDefault(c => c.Id==id);
           // var categoryFromDb = _db.Categories.Find(id);
            if (categoryFromFirstORDefaultDb == null)
            {
                return NotFound();
            }

            return View(categoryFromFirstORDefaultDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the name");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
              var categoryFromFirstORDefaultDb= _unitOfWork.Category.GetFirstOrDefault(c => c.Id==id);
            //  var categoryFromSingleOrDefaultDb= _db.Categories.SingleOrDefault(c => c.Id==id);
           // var categoryFromDb = _db.Categories.Find(id);
            if (categoryFromFirstORDefaultDb == null)
            {
                return NotFound();
            }
            return View(categoryFromFirstORDefaultDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var category = _unitOfWork.Category.GetFirstOrDefault(c=>c.Id==id);

            if (category==null)
            {
                return NotFound();
            }
            _unitOfWork.Category.Remove(category);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");


        }

    }
}

BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using BulkyBook.Models.ViewModel;
using Microsoft.AspNetCore.Hosting;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        readonly IUnitOfWork _unitOfWOrk;
       

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWOrk = unitOfWork;
           
        }
        public IActionResult Index()
        {
          //  IEnumerable<CoverType> coverTypes = _unitOfWOrk.CoverType.GetAll();
            return View();
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            Company company = new();

            if (id == 0 || id == null)
            {
                // ViewBag.CategoryList=CategoryList;// Use of Viewbag
                // ViewData["CoverTypeList"] = CoverTypeList;
                //Create();
                return View(company);
            }
            else
            {
                company= _unitOfWOrk.Company.GetFirstOrDefault(u=>u.Id==id);
                return View(company);
                //Update();
            }       
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpSert(Company company)
        {
            if (ModelState.IsValid)
            {
                
                if (company.Id==0)
                {
                    _unitOfWOrk.Company.Add(company);
                    TempData["success"] = "Category created successfully";
                }
                else
                {
                    _unitOfWOrk.Company.Update(company);
                   TempData["success"] = "Category updated successfully";
                }
                _unitOfWOrk.Save();
                
                return RedirectToAction("Index");
            }
            return View(company);
        }
        //GET
      /*  public IActionResult Delete(int? id)
        {

            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var coverType = _unitOfWOrk.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var coverType = _unitOfWOrk.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }
            _unitOfWOrk.CoverType.Remove(coverType);
            _unitOfWOrk.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
      */

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var companyList = _unitOfWOrk.Company.GetAll();
            return Json(new {data=companyList});
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var company = _unitOfWOrk.Company.GetFirstOrDefault(c => c.Id == id);
            if (company == null)
            {
                return Json(new {success=false,message="Error while deleting"});
            }
        
            _unitOfWOrk.Company.Remove(company);
            _unitOfWOrk.Save();
            // TempData["success"] = "Category deleted successfully";
            return Json(new { success = true, message = "Deleted successfully" });
        }

        #endregion
    }
}

BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using Microsoft.AspNetCore.Mvc;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.DataAccess.Repository.IRepository;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        readonly IUnitOfWork _unitOfWOrk;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWOrk = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> coverTypes = _unitOfWOrk.CoverType.GetAll();
            return View(coverTypes);
        }

        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType coverType)
        {
            if (ModelState.IsValid)
            {
                _unitOfWOrk.CoverType.Add(coverType);
                _unitOfWOrk.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(coverType);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            if (id==0 || id==null)
            {
                return NotFound();
            }
            var coverType= _unitOfWOrk.CoverType.GetFirstOrDefault(c=>c.Id==id);
            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType coverType)
        {
            if (ModelState.IsValid)
            {

                _unitOfWOrk.CoverType.Update(coverType);
                _unitOfWOrk.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(coverType);
        }
        //GET
        public IActionResult Delete(int? id)
        {

            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var coverType = _unitOfWOrk.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var coverType = _unitOfWOrk.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (coverType==null)
            {
                return NotFound();
            }
            _unitOfWOrk.CoverType.Remove(coverType);
            _unitOfWOrk.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using BulkyBook.Models.ViewModel;
using Microsoft.AspNetCore.Hosting;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        readonly IUnitOfWork _unitOfWOrk;
        readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWOrk = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
          //  IEnumerable<CoverType> coverTypes = _unitOfWOrk.CoverType.GetAll();
            return View();
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new ProductVM()
            {
                Product = new(),
                CategoryList = _unitOfWOrk.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                CoverTypeList = _unitOfWOrk.CoverType.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
            };

            if (id == 0 || id == null)
            {
                // ViewBag.CategoryList=CategoryList;// Use of Viewbag
                // ViewData["CoverTypeList"] = CoverTypeList;
                //Create();
                return View(productVM);
            }
            else
            {
                productVM.Product = _unitOfWOrk.Product.GetFirstOrDefault(u=>u.Id==id);
                return View(productVM);
                //Update();
            }


           
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpSert(ProductVM productVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file!=null)
                {                 
                    string fileName=Guid.NewGuid().ToString();
                    string upload=Path.Combine(wwwRootPath, @"images\products");
                    string extenstion=Path.GetExtension(file.FileName);
                    if (productVM.Product.ImageUrl!=null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, productVM.Product.ImageUrl.Trim('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(upload, fileName + extenstion), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    productVM.Product.ImageUrl = @"\images\products\" + fileName + extenstion;
                }
                if (productVM.Product.Id==0)
                {
                    _unitOfWOrk.Product.Add(productVM.Product);
                   
                }
                else
                {
                    _unitOfWOrk.Product.Update(productVM.Product);
                    //TempData["success"] = "Category updated successfully";
                }
                _unitOfWOrk.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(productVM);
        }
        //GET
      /*  public IActionResult Delete(int? id)
        {

            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var coverType = _unitOfWOrk.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var coverType = _unitOfWOrk.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }
            _unitOfWOrk.CoverType.Remove(coverType);
            _unitOfWOrk.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
      */

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWOrk.Product.GetAll(includeProperties:"Category,CoverType");
            return Json(new {data=productList});
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var product = _unitOfWOrk.Product.GetFirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return Json(new {success=false,message="Error while deleting"});
            }
            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, product.ImageUrl.Trim('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWOrk.Product.Remove(product);
            _unitOfWOrk.Save();
            // TempData["success"] = "Category deleted successfully";
            return Json(new { success = true, message = "Deleted successfully" });
        }

        #endregion
    }
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/css//bootsWatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                            <span class="visually-hidden">(current)</span>
                        </li>
                        <li class="nav-item">

                        </li>
                        <li class="nav-item">

                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                 <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                    @* <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search" spellcheck="false" data-ms-editor="true">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" /> @*use here if needed across many pages*@
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - BulkyBookWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/jnsq5gcjn7rmql6g438xms9o151bo7woa3d8lof4vtqypux0/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookWeb/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src=~/lib/jquery/dist/jquery.min.js> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.success('@TempData["success"]')

    </script>
}
@if(TempData["error"]!=null)
{
    <script src=~/lib/jquery/dist/jquery.min.js> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
    toastr.success('@TempData["error"]')

    </script>
}